#!/bin/sh

trap do_stop INT TERM KILL STOP
do_stop() {
    echo "STOPPING SELENIUM AT $SELENIUM_PID"
    kill $SELENIUM_PID
    exit 0
}
su nathan -c "java -jar /opt/selenium/selenium-server.jar &"
SELENIUM_PID=$!
while true; do
    sleep 1
done