#!/bin/sh

DESC="Selenium Server"
NAME=selenium
export DISPLAY=:0.0
export XAUTHORITY=/home/nathan/.Xauthority
export HOME=/home/nathan

do_start() {
    touch /var/log/selenium
    chmod a+rw /var/log/selenium
    java -jar /opt/selenium/selenium-server.jar -firefoxProfileTemplate /opt/selenium/profile/ &
    echo -n $! | cat > /var/run/selenium.pid
}

do_stop() {
    echo "STOPPING SELENIUM SERVER"
    kill $(cat /var/run/selenium.pid)
    rm /var/run/selenium.pid
}

case $1 in
    start)
	echo -n "Starting $DESC: $NAME"
	do_start
	echo "."
	;;
    stop)
	echo -n "Stopping $DESC : $NAME"
	do_stop
	echo "."
	;;
    restart)
	echo -n "Restarting $DESC : $NAME"
	do_stop
	sleep 1
	do_start
	echo "."
	;;
    *)
	echo "usage: $NAME {start|stop|restart}"
	exit 1
	;;
esac