#!/bin/sh

DESC="Selenium Server"
NAME=selenium
PIDFILE=/var/run/$NAME.pid
export DISPLAY=:0.0
export XAUTHORITY=/home/nathan/.Xauthority
export HOME=/home/nathan

do_start() {
    touch /var/log/selenium
    chmod a+rw /var/log/selenium
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec /usr/bin/java -- -jar /opt/selenium/selenium-server.jar -firefoxProfileTemplate /opt/selenium/profile/
}

do_stop() {
    start-stop-daemon --stop --pidfile $PIDFILE
    if [ -e $PIDFILE ]
    then rm $PIDFILE
    fi
}

case $1 in
    start)
	echo -n "Starting $DESC: $NAME"
	do_start
	echo "."
	;;
    stop)
	echo -n "Stopping $DESC : $NAME"
	do_stop
	echo "."
	;;
    restart)
	echo -n "Restarting $DESC : $NAME"
	do_stop
	sleep 1
	do_start
	echo "."
	;;
    *)
	echo "usage: $NAME {start|stop|restart}"
	exit 1
	;;
esac