#!/bin/sh

trap do_stop INT TERM KILL STOP
do_stop() {
    echo "STOPPING HUDSON AT $HUDSON_PID"
    kill $HUDSON_PID
    exit 0
}
java -jar /opt/hudson/hudson.war &
HUDSON_PID=$!
while true; do
    sleep 1
done